// app/layout.tsx

"use client";

import React, { ReactNode } from "react";
import "../styles/globals.css"; // 글로벌 스타일 시트
import { usePathname } from "next/navigation";
import { SessionProvider } from "next-auth/react";
import Navbar from "@/components/Navbar";

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) => {
  const pathname = usePathname();

  // accounts 경로인지 확인
  const isAccountsPath = pathname.startsWith("/accounts");

  return (
    <html lang="en" className="bg-[#1c1c1f] text-white w-full h-full">
      <head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="flex flex-col min-h-screen">
        <SessionProvider>
          {!isAccountsPath && <Navbar />}
          <main className="flex-grow">{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
};

export default RootLayout;
